[theme]
primaryColor = "#003876"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6FA"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
